language: swift
osx_image: xcode11.6
before_install:
  - yes | gem update --system --force
  - gem install bundler
  - brew install libsodium
install:
  - bundle install
script:
  - fastlane build_and_test
